#!/bin/bash

## for installing additional non-ROS2 dependencies to debian package generated by bloom


if [ ! -e /etc/ros/rosdep/sources.list.d/20-default.list ]; then
        echo "--- Initialize rosdep"
        sudo rosdep init
fi

mod_dir=$(echo $1 | sed 's/\/$//')

yamlpath=""
if [ -e ${mod_dir}/rosdep.yaml ]; then
    yamlpath=${mod_dir}/rosdep.yaml
elif [ -e ${mod_dir}/packaging/rosdep.yaml ]; then
    yamlpath=${mod_dir}/packaging/rosdep.yaml
fi

if [ "$yamlpath" != "" ]; then
    echo "--- Add module specific dependencies"
    cat $yamlpath
    mkdir -p /etc/ros/rosdep/sources.list.d
    echo "yaml file://${yamlpath}" > /etc/ros/rosdep/sources.list.d/51-fogsw-module.list
fi

echo "--- Updating rosdep"
rosdep update
# Dependencies from fog-sw repo
if [ -e ${mod_dir}/ros2_ws/src ]; then
    pushd ${mod_dir}/ros2_ws
    source /opt/ros/${ROS_DISTRO}/setup.bash
else
    mkdir -p ${mod_dir}/deps_ws/src
    pushd ${mod_dir}/deps_ws
    vcs import src < ${mod_dir}/underlay.repos
    rosdep install --from-paths src --ignore-src -r -y --rosdistro ${ROS_DISTRO}
    source /opt/ros/${ROS_DISTRO}/setup.bash
fi
colcon build --packages-select fog_msgs
popd

exit 0
